/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavBar: typeof import('./components/AppNavBar.vue')['default']
    AppPage: typeof import('./components/AppPage.vue')['default']
    AppStatusBar: typeof import('./components/AppStatusBar.vue')['default']
    CheckBox: typeof import('./components/CheckBox.vue')['default']
    LinkTo: typeof import('./components/LinkTo.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
  }
}
